#!/bin/sh

[ -r /lib/functions/system.sh ] && . /lib/functions/system.sh

[ -f /lib/functions/cambium-sage.sh ] || exit 0
. /lib/functions/cambium-sage.sh
cambium_sage_board && [ "$SAGE_QUALIFIED" = 1 ] || exit 0

uci -q set irqbalance.@irqbalance[0].enabled='1'
uci -q commit irqbalance

/etc/init.d/sage-sysupgrade-mark-good enable

exit 0
